### ISSUE TITLE
Run python script using Pyrolite

### ISSUE THREAD

**Issue by lasidaputhunattil** [irmen/Pyrolite#17]
Hi,

I have a simple python script in my local machine, which returns a string. I want to run this script from java application and get the return value. I'm trying to do this using Pyrolite. I downloaded the jar files and added them to my java class path. But I'm not able to run the script.

I got the below sample code from readme.txt

NameServerProxy ns = NameServerProxy.locateNS(null);
PyroProxy remoteobject = new PyroProxy(ns.lookup("Your.Pyro.Object"));
Object result = remoteobject.call("pythonmethod", 42, "hello", new int[]{1,2,3});
String message = (String)result;  // cast to the type that 'pythonmethod' returns
System.out.println("result message="+message);
remoteobject.close();
ns.close();

But this is not working for me. My system configuration is

OS: Windows 8
JDK: jdk1.7.0_51
Python: 2.6

Please help me with this.

**Comment by irmen** [comment]
You're not very helpful. It's impossible to assist if you don't provide extra info such as:

- the exact error message you're getting including stacktrace, if any
- what did you expect to happen? what did you try by yourself already?
- how does your server code look like and how are you running everything?

p.s. while Pyro still supports it, Python 2.6 is very old. Any particular reason you're still using this old version instead of 2.7 or 3.x?

**Comment by lasidaputhunattil** [comment]
Hi,

Sorry for providing insufficient information. This is what I tried till now:

        NameServerProxy ns = NameServerProxy.locateNS(null);
        PyroProxy remoteobject = new PyroProxy();
        Object result = remoteobject.call("C:\\trail.py", null);
        String message = (String)result; 
        System.out.println("result message="+message);
        remoteobject.close();
        ns.close();

but it is giving be following error:
        java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at net.razorvine.pyro.PyroProxy.connect(PyroProxy.java:72)
	at net.razorvine.pyro.PyroProxy.internal_call(PyroProxy.java:196)
	at net.razorvine.pyro.PyroProxy.call(PyroProxy.java:161)
	at tryPyrolite.pyrotry.main(pyrotry.java:15)

Since the script is in my own local machine I thought this is enough, but something I'm missing out. 
Since our whole backend still work on Python 2.6, I cant upgrade my python. 

Also my sample python script is this:
import ctypes
p=ctypes.create_string_buffer('Hello')
print p.value

Please tell me if you need more information to help me out with this. I'm stuck with this from past 1 week.

**Comment by irmen** [comment]
Seems like you're confused as to what you want to do: you're using the wrong tool for the job.

Pyrolite is not for executing arbitrary python programs on the local machine. It is meant to connect *over the network* to a long running python process via the Pyro protocol.

My guess is you wanna use Runtime.exec() or ProcessBuilder instead.
