### ISSUE TITLE
possible decode_escaped problem with unsupported escape sequences

### ISSUE THREAD

**Issue by irmen** [irmen/Pyrolite#20]
pickling datetime.datetime(2014, 7, 8, 10) gives a pickle with a S opcode containing a "\n" as escaped character in the string. decode_escaped seems unable to deal with this.
See issue #19  for details

pickling datetime.datetime(2014, 10, 10, 10, 0) gives even more \n's in the string obviously

The byte values that will cause problems are the ones that are encoded by python using one of the standard escape characters rather than a hexadecimal escape:

9 -> \t
10 -> \n
13 -> \r
See the output of
```
import pprint; pprint.pprint({i:chr(i) for i in range(33)})
```

Also, what about decode_unicode_escaped (which is called from the load_unicode opcode)? Seems like it has to be able to deal with the same escaped characters...

**Comment by airhorns** [comment]
Ah, I think I figured this one out:

This pickle string throws the error reading exactly like this in the Java source:
```java
		pc=(Calendar) U("cdatetime\ndatetime\np0\n(S\'\\x07\\xde\\x07\\x08\\n\\x00\\x00\\x00\\x00\\x00\'\np1\ntp2\nRp3\n.");
```

but this one doesn't

```java
		pc=(Calendar) U("cdatetime\ndatetime\np0\n(S\'\\x07\\xde\\x07\\x08\\x0A\\x00\\x00\\x00\\x00\\x00\'\np1\ntp2\nRp3\n.");
```

the difference being that the newline character actually needs to be encoded as `\x0A`, decimal 10, which the python interpreter encodes as `\\n` in the console output of `str.encode('string-escape')` which is what I was copy pasting into the terminal. If I hex dump the output of 

```python
pickle.dump(datetime.datetime(2014, 7, 8, 10, 10, 10, 10, utc), sys.stdout)
```

it gives:

```
oration ~/C/starscream starscream (bump_0694e4be) ➜  python tests/work/date_pickling.py | hexdump -C
00000000  63 64 61 74 65 74 69 6d  65 0a 64 61 74 65 74 69  |cdatetime.dateti|
00000010  6d 65 0a 70 30 0a 28 53  27 5c 78 30 37 5c 78 64  |me.p0.(S'\x07\xd|
00000020  65 5c 78 30 37 5c 78 30  38 5c 6e 5c 6e 5c 6e 5c  |e\x07\x08\n\n\n\|
00000030  78 30 30 5c 78 30 30 5c  6e 27 0a 70 31 0a 63 70  |x00\x00\n'.p1.cp|
00000040  79 74 7a 0a 5f 55 54 43  0a 70 32 0a 28 74 52 70  |ytz._UTC.p2.(tRp|
00000050  33 0a 74 70 34 0a 52 70  35 0a 2e 0a              |3.tp4.Rp5...|
```

which means I think that python is actually encoding the decimal 10 as \n in the string. Patch and better proof forthcoming.

**Comment by irmen** [comment]
yeah see my updated comment above, this also counts for \t and \r.
