### ISSUE TITLE
add pickling support for java 8's java.time API

### ISSUE THREAD

**Issue by irmen** [irmen/Pyrolite#24]
Pickler only supports the old style time/calendar objects.
We probably need to support java 8's java.time API as well.

An interesting issue arises for unpickling: to what objects should we unpickle? 
Make it configurable?  Autoselect based on JDK version?

Also how do we ensure that the class file still works on JDK 1.7?

**Comment by irmen** [comment]
@airhorns  do you have any suggestions perhaps on this matter?

**Comment by airhorns** [comment]
I sadly do not, my strengths are on the python side, but maybe @kmtaylor-github @udnay or @drdee could help!

**Comment by irmen** [comment]
Seems too much hassle for too little gain at this  time.  Java 7 is still the baseline version supported.
