### ISSUE TITLE
java: Class name initialization and retrieval

### ISSUE THREAD

**Issue by vruusmann** [irmen/Pyrolite#38]
Is there a specific reason why the constructor `ClassDict(String, String)` does not initialize the `__class__` attribute value? I have a situation where I need to invoke the method `ClassDict#__setstate__(Map)` with an empty `HashMap` instance to have a newly constructed `ClassDict` instance properly initialized.

Also, would it be possible to expose the field `ClassDict#classname` via a getter method? This method could specify `protected` access modifier if you don't want to clutter the public API.

**Comment by irmen** [comment]
Why are you creating instances of ClassDict yourself? You're not really supposed to do that. They are created by the unpickler (via ClassDictConstructor) for you if it encounters a custom class in the pickle stream.

**Comment by vruusmann** [comment]
I'm mostly interested in unpickling Scikit-Learn classes. The problem is that some Scikit-Learn classes reference CPython classes. I decided to isolate CPython code to a separate class hierarchy by introducing a class `CClassDict` (which is a subclass of `ClassDict`). The initialization of my `CClassDict` objects is done using Java reflection, and it involves invoking `__init__(Object[])` on a newly constructed object instance (see method `ExtensionObjectConverter#construct(Object[])`):
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/org/jpmml/sklearn/ExtensionObjectConstructor.java

Perhaps I just missed the right way of handling CPython objects.

**Comment by irmen** [comment]
I see, that makes sense. I'll look into fixing the constructor.
