### ISSUE TITLE
java: Relax the visibility of `Unpickler.NO_RETURN_VALUE` class constant

### ISSUE THREAD

**Issue by vruusmann** [irmen/Pyrolite#50]
Related to issue #49. Currently, I'm working around the `private` access control like this:
```Java
public static Object noReturnValue(){
	try {
		Field field = Unpickler.class.getDeclaredField("NO_RETURN_VALUE");
		if(!field.isAccessible()){
			field.setAccessible(true);
		}
		return field.get(null);
	} catch(Exception e){
		throw new RuntimeException(e);
	}
}
```

**Comment by irmen** [comment]
uggh, nifty hack :)  Will make it protected, I guess you're needing it in a subclass of Unpickler?

**Comment by irmen** [comment]
made remaining private fields protected in commit 7b20264bfecc7cff7862b3a7dc8c8af6b4b24f9f

**Comment by vruusmann** [comment]
This class constant should have the same visibility as the `Unpickler#stack` instance field. And `protected` is better than `<package private>`, because there are legitimate scenarios where one might want to subclass `Unpickler` and manipulate its state.

**Comment by vruusmann** [comment]
While we're at it, then I also have a scenario where I'm using reflection to access `net.razorvine.pickle.objects.ClassDictConstructor#module` and `net.razorvine.pickle.objects.ClassDictConstructor#name` fields in my application code.

I'm using it to perform programmatic "bulk mapping" from Python classes to Java classes. I know that you've introduced a special API for that in newest Pyrolite versions, but I haven't had a chance to research this area properly. Reflection did it for me at the moment.

**Comment by irmen** [comment]
It is not clear to me why you have to access those two fields again. They're passed as-is to the ``ClassDictConstructor``'s constructor when it's created and I assume you do the same if you subclass it yourself. So you already know the values of both fields beforehand, no?

The API to convert custom classes is really simple, it's also based on the same two values actually!  You register your own class creator instance for the given module+class name using the ``Unpickler.registerConstructor`` method.
