### ISSUE TITLE
java(?): Method `PickleUtils.decode_escaped` doesn't recognize all escaped characters

### ISSUE THREAD

**Issue by vruusmann** [irmen/Pyrolite#51]
The original issue: 
https://github.com/jpmml/jpmml-sklearn/issues/27

A reproducible test case `finalized_model.txt` (should be renamed `finalized_model.pkl` locally) is available here: https://github.com/jpmml/jpmml-sklearn/issues/27#issuecomment-276355598

I did some debugging, and discovered that the problem is related to escape sequence `\'`. Attached is a patchfile against the latest Pytholite version `4.17-SNAPSHOT`, which provides a temporary workaround.
[decode.patch.txt](https://github.com/irmen/Pyrolite/files/742107/decode.patch.txt)

**Comment by irmen** [comment]
Oh hmmm why is that system writing pickles in protocol 0 anyway? That's very inefficient... (and the cause of the bug in pyrolite, I'm quite certain the decoding of strings in pickle protocols 1 and up is fine)

**Comment by irmen** [comment]
Fixed it for both java and dotnet, added some new unit tests for it as well.
