### ISSUE TITLE
unit test TestUnpickleProto0Bytes fails on Windows

### ISSUE THREAD

**Issue by irmen** [irmen/Pyrolite#60]
TestUnpickleProto0Bytes() fails on Windows due to \r\n line ending issue

**Comment by irmen** [comment]
should be fixed via 1fb9ac4c2bb9def6bb2e9d7642deff7b2e53d84f  @stephentoub  can you verify this?

**Comment by stephentoub** [comment]
> @stephentoub can you verify this?

Yup:
![image](https://user-images.githubusercontent.com/2642209/56401657-f7abf880-6227-11e9-8202-25dc7036a48e.png)
