### ISSUE TITLE
Is there same thing like "@Pyro4.expose" in Pyrolite?

### ISSUE THREAD

**Issue by XuMengchu** [irmen/Pyrolite#61]
I can call method and get value from server.
Is there same thing like "@Pyro4.expose" in Pyrolite?
I want to expose C# method and let server call C# client method.

**Comment by irmen** [comment]
No, Pyrolite is strictly a _client_ library. 

Remotely calling code in C# (or another language) is not the field of Pyro and Pyrolite. Look into language specific RPC mechanisms or perhaps even web services.
