### ISSUE TITLE
Strong-name sign the C# assembly?

### ISSUE THREAD

**Issue by stephentoub** [irmen/Pyrolite#62]
Would it be possible for you to strong-name sign the managed assembly?  That's necessary for other strong-named assemblies to be able to reference it.

**Comment by irmen** [comment]
... I must confess that I don't really know what this is or how I go about doing it. Can you give me some relevant pointers on how I can proceed?

**Comment by stephentoub** [comment]
I put up a PR for it if you decide you want to go ahead with it: https://github.com/irmen/Pyrolite/pull/63.

All I did was:
1. Open the .csproj in Visual Studio.
2. Right-click on the project in Solution Explorer and select Properties.
3. Click on the Signing tab, click "Sign the Assembly", select "<New...>" from the drop-down, enter the name of a new file, uncheck "Protect with password", and click ok.

**Comment by irmen** [comment]
I'll have to figure out how to do this with the tools I'm using on my system (Linux with Rider and dotnet core).

**Comment by irmen** [comment]
@stephentoub I suppose the same holds for the dependent library Razorvine.Serpent ?

**Comment by stephentoub** [comment]
>  I suppose the same holds for the dependent library Razorvine.Serpent ?

Yup.  I assume that's this?
https://github.com/irmen/Serpent/tree/master/dotnet/Serpent/Razorvine.Serpent
If you'd like to go ahead with this, I can submit a PR there as well if it would help.

**Comment by irmen** [comment]
That's the one. I think I got it, have a look at commit irmen/serpent@763a6e15f75c4d5937cd16dfc70b0930a442b541 over there.
