### ISSUE TITLE
Potential error with pyrolite maven dependency

### ISSUE THREAD

**Issue by ghaddarAbs** [irmen/Pyrolite#73]
This happened recently .....pyrolite couldn't be imported as a java dependency with maven anymore:
```
<dependency>
            <groupId>net.razorvine</groupId>
            <artifactId>pyrolite</artifactId>
            <version>4.4</version>
</dependency>
```
Because it depends on serpent version 1.10 that was removed from maven center (recently as I think). Here is the error message when i try to import pyrolite using maven (also it dosn't work with other pyrolite versions):

```
Could not transfer artifact net.razorvine:serpent:pom:1.10 from/to central (https://repo.maven.apache.org/maven2): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by irmen** [comment]
Pyrolite 4.4 is an ancient version that shouldn't be used anymore. Also I don't think serpent 1.10 (and older) has ever been on maven central, these are also ancient versions.

The solution is to upgrade to a more recent Pyrolite version, preferrably the latest (4.30 at this time of writing)
