### ISSUE TITLE
Batch calls support

### ISSUE THREAD

**Issue by fridayzz** [irmen/Pyrolite#77]
How can we bundle small calls in batch and get all the result once for all to avoid round trip latency in c# client lib? I’m aware pyro support that. However, it seems not supported in Pyrolite.

Thanks

**Comment by irmen** [comment]
Indeed, this is a feature not implemented in the current Pyrolite.
Maybe I'll add it when adapting Pyrolite to be compatible with Pyro5.

**Comment by irmen** [comment]
I won't be adding this feature myself, sorry.
